---
run:
  timeout: 15m

linters:
  # additional linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - containedctx
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gofmt
    - goimports
    - gosec
    - grouper
    - makezero
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - tenv
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

issues:
  exclude: []
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - goconst
    - path: '(.+)_test\.go'
      linters:
        - govet
      text: 'fieldalignment: .*'
  exclude-files:
    - internal/model/openconfig/oc_path.go
    - internal/model/openconfig/oc.go
    - internal/model/ietf/ietf.go
