version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - containedctx
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - grouper
    - makezero
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
      - linters:
          - govet
        path: (.+)_test\.go
        text: 'fieldalignment: .*'
    paths:
      - internal/model/openconfig/oc_path.go
      - internal/model/openconfig/oc.go
      - internal/model/ietf/ietf.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/model/openconfig/oc_path.go
      - internal/model/openconfig/oc.go
      - internal/model/ietf/ietf.go
      - third_party$
      - builtin$
      - examples$
